const data = {
  products: [
    {
      name: "Turtle Shirt",
      slug: "turtle-shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 1200,
      counInStock: 10,
      brand: "Turtle",
      rating: 4.5,
      numReviews: 10,
      desc: "Good shirt",
    },
    {
        name: "Turtle Shirt",
        slug: "turtle-shirt",
        category: "Shirts",
        image: "/image/p2.jpg",
        price: 1200,
        counInStock: 10,
        brand: "Turtle",
        rating: 4.5,
        numReviews: 10,
        desc: "Good shirt",
      },
      {
        name: "Turtle pant",
        slug: "turtle-pant",
        category: "pants",
        image: "/image/p3.jpg",
        price: 1200,
        counInStock: 10,
        brand: "Turtle",
        rating: 4.5,
        numReviews: 10,
        desc: "Good pant",
      },
      {
        name: "Turtle pant",
        slug: "turtle-pant",
        category: "pants",
        image: "/image/p4.jpg",
        price: 1200,
        counInStock: 10,
        brand: "Turtle",
        rating: 4.5,
        numReviews: 10,
        desc: "Good pant",
      },
  ],
};
export default data;
